#!/usr/bin/env bash
#  -----------------------------------------------------------------------------
#  Lint Script — Static Analysis for `{{ .ProjectName }}`
#  -----------------------------------------------------------------------------
#
#  It is intended to ensure consistent code quality across environments.
#
#  Linters are dynamically injected during scaffolding based on project config.
#
#  Usage:
#    ./scripts/lint.sh
#
#  Requirements:
#    - Any linters marked as "local" must be installed on the host
#    - Markdownlint is run via Docker (no local install needed)
#
#  File generated by goboot — do not modify manually.
#  -----------------------------------------------------------------------------

set -euo pipefail

echo "Starting lint process for '{{ .ProjectName }}'..."
echo ""

{{- $linters := index .TaskScripts "base_lint" }}
{{- if not $linters }}
echo "No linters are currently configured. Nothing to do."
exit 0
{{- else }}
# -----------------------------------------------------------------------------
# Execute Enabled Linters
# -----------------------------------------------------------------------------
{{- range $linter := $linters }}

echo "Running: {{ $linter }}"
{{ $linter }}
echo "✓ Done: {{ $linter }}"
echo ""
{{- end }}

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

echo "All configured linters completed successfully."
exit 0
{{- end }}
