#  markdown configuration for consistent and readable md files.

default: true  #  Start with markdownlint’s default rule set

#  --- Line length ---
MD013:
  line_length: 120    # Enforce readable line width
  code_blocks: false  # Allow long lines inside code blocks
  tables: false       # Allow wide tables (often needed for clarity)

#  --- Raw HTML / heading flexibility ---
MD033: false  #  Allow raw HTML in Markdown (useful for badges, embeds, HTML layout tweaks)
MD034: false  #  Allow unescaped HTML tags (e.g., <br>, <sup>) when needed
MD024: false  #  Allow duplicate headings as long as content differs (common in changelogs or grouped sections)
MD025: false  #  Allow multiple top-level headings (some docs use multiple sections, not a single H1)

#  --- Headings ---
MD041: true  #  Require the first line to be a top-level heading (usually `# ProjectName`)
MD022: true  #  Enforce blank lines around headings for consistency
MD018:
  style: atx  #  Enforce ATX-style headings (`#`) — consistent and GitHub-friendly

#  --- Lists ---
MD004:
  style: dash  #  Use `-` for all unordered list items for consistency across files
MD007:
  indent: 2  #  Enforce 2-space indentation in nested lists (common OSS standard)
MD029:
  style: ordered  #  Ensure numbered lists increment properly (e.g., 1., 2., 3.)

#  --- Emphasis and links ---
MD036: true  #  Disallow emphasis used as a header (e.g., *bold* instead of ## bold)

# --- Spacing and padding ---
MD012: true  #  No multiple consecutive blank lines
MD019: true  #  Ensure no space after hash in headings (e.g., "#Heading" → invalid)

#  --- Consistency ---
MD026: true  #  No trailing punctuation in headers (e.g., avoid `## Features:`)
