#  yamllint configuration for consistent and readable YAML files.

extends: default  #  Start from yamllint's default rules

#  ignore specific template files which are invalid in the raw format
#  ignore: |
#    templates/local_base/.pre-commit-config.yaml

rules:
  #  --- Line length ---
  line-length:
    max: 145                         #  Allow longer lines (e.g., badge URLs, messages)
    allow-non-breakable-words: true  #  Don't flag long words like URLs

  #  --- Document formatting ---
  document-start: disable  #  Don’t require "---" at the start of each YAML file
  document-end: disable    #  Allow files to omit "..." at the end

  #  --- Indentation ---
  indentation:
    spaces: 2                     #  Enforce 2-space indentation (standard in OSS)
    indent-sequences: consistent  #  Keep a consistent list indentation

  #  --- Spacing ---
  trailing-spaces: disable  #  Allow trailing spaces (useful in Markdown-like YAML)
  new-lines:
    type: unix  #  Enforce LF line endings (cross-platform friendly)
  empty-lines:
    max: 2  #  Allow some visual spacing but keep it correct

  #  --- Quoting ---
  truthy:
    allowed-values: ['true', 'false']  #  Allow common boolean aliases
    check-keys: false                  #  Only check values, not key names

  #  --- Comments ---
  comments-indentation: enable  #  Ensure comments are aligned with content
  comments:
    require-starting-space: true  #  Force space after `#` (readability)
