#  -----------------------------------------------------------------------------
#  🛠 Taskfile — Developer Commands for `goboot`
#  -----------------------------------------------------------------------------
#
#  This file defines reproducible and documented task aliases for common workflows.
#  It is used by the `go-task` tool (https://taskfile.dev/) and acts as a modern
#  alternative to Makefiles — with cleaner syntax, native YAML support, and built-in shell integration.
#
#  These tasks are intended to:
#    - Simplify setup and usage for contributors
#    - Ensure consistent linting and testing across environments
#    - Act as automation hooks for CI pipelines or local workflows.
#
#  This file is part of the `goboot` template project and may require
#  adaptation in downstream OSS or private forks.

version: "3"

# -----------------------------------------------------------------------------
# 🔄 Dynamic variables
# -----------------------------------------------------------------------------
vars:
  VERSION:
    sh: cat .version  #  Reads a version from a file (used for builds and prints)

  MD_FILES:
    sh: find . -name '*.md' | tr '\n' ' '
  SH_FILES:
    sh: find . -type f -name '*.sh' | tr '\n' ' '

  DOCKER_RUN_CMD: "docker run --rm -v {{.ROOT_DIR}}:/workdir -w /workdir"

  # Go / project linters
  GOLANGCI_LINT_CMD: '{{.DOCKER_RUN_CMD}} golangci/golangci-lint:v2.7.1 golangci-lint run cmd/... pkg/...'
  YAML_LINT_CMD: '{{.DOCKER_RUN_CMD}} pipelinecomponents/yamllint:0.35.9 yamllint .'
  CHECKMAKE_LINT_CMD: '{{.DOCKER_RUN_CMD}} cytopia/checkmake:latest-0.5 Makefile'
  MD_LINT_CMD: '{{.DOCKER_RUN_CMD}} ghcr.io/igorshubovych/markdownlint-cli:v0.46.0 markdownlint {{.MD_FILES}}'

  # Shell tooling
  SHELLCHECK_CMD: '{{.DOCKER_RUN_CMD}} koalaman/shellcheck:v0.11.0 -x {{.SH_FILES}}'
  SHFMT_CHECK_CMD: '{{.DOCKER_RUN_CMD}} mvdan/shfmt:v3.12.0 -d -i 2 -ci {{.SH_FILES}}'

  TEST_COVER_FILE: "coverage.txt"

#  -----------------------------------------------------------------------------
#  📋 Defined Tasks
#  -----------------------------------------------------------------------------
tasks:
  default:
    desc: Run build, lint, and test (default task)
    deps: [build, lint, test]  #  Combines common developer workflows

  build:
    desc: Build the Go binary
    cmd: go build -ldflags="-X main.version={{.VERSION}}" -o bin/goboot ./cmd/goboot
    #  - `-X`: inject version string into the `main.version` variable

  lint:
    desc: Run linters
    cmds:
      - '{{.GOLANGCI_LINT_CMD}}'   #  Static analysis for all Go source files
      - '{{.YAML_LINT_CMD}}'       #  YAML syntax and formatting
      - '{{.CHECKMAKE_LINT_CMD}}'  #  Lint for Makefile syntax / conventions
      - '{{.MD_LINT_CMD}}'         #  Markdown lint via container
      - '{{.SHELLCHECK_CMD}}'      #  ShellCheck for shell scripts
      - '{{.SHFMT_CHECK_CMD}}'     #  shfmt for shell scripts (check only)

  test:
    desc: Run all tests with coverage
    cmds:
      - |
          TEST_PKGS="$(
            go list ./... \
              | grep -v "/test/noauto" \
              | grep -v "/templates"
          )"

          go test \
            -race \
            -timeout=9m \
            -coverprofile "{{.TEST_COVER_FILE}}" \
            ${TEST_PKGS}
      - go tool cover -func="{{.TEST_COVER_FILE}}"
      - rm -f "{{.TEST_COVER_FILE}}"

  version:
    desc: Print current version
    cmd: 'echo "Current version: {{.VERSION}}"'
