###############################################################################
# {{.ProjectName}} Configuration File
#
# This file defines ...
#
###############################################################################

# ------------------------------------------------------------------------------
# Some Section
# ------------------------------------------------------------------------------

# Some description
some_var: "..."
