# Config for the `base_test` service.
# Safe to commit; no secrets.

# Template source.

#  Directory where the templates will be read from.
sourcePath: "templates/test_base"

# Test behavior.

#  Use style for test files; currently only "ginkgo" and "go" are supported.
useStyle: "ginkgo"

#  Command to run tests. If empty, goboot fills in the default command.
testCmd: |-
  go test -race -timeout=5m -coverprofile=coverage.txt ./... &&
  go tool cover -func=coverage.txt &&
  rm -f coverage.txt
