name: Lint

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        # Used commit SHA for actions/checkout@v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run golangci-lint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            golangci/golangci-lint@sha256:5d6d5c70a61f1356adfd9dd6316ce286799fefc9d743421356ff1b00842368ba \
            golangci-lint run ./...

      - name: Run yamllint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            pipelinecomponents/yamllint@sha256:3e9eb9bef568b904d9222e9174a1490f4e015aef3d61e7d3e56f60035e517b79 \
            yamllint .

      - name: Run markdownlint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            ghcr.io/igorshubovych/markdownlint-cli@sha256:9f06c8c9a75aa08b87b235b66d618f7df351f09f08faf703177f670e38ee6511 \
            "**/*.md"

      - name: Run checkmake
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            cytopia/checkmake@sha256:23116ee551144f1021b294d3ede266ecb760272e0d6f2833f8a3d38b81beffb8 \
            Makefile

      - name: Run shellcheck
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            koalaman/shellcheck@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d \
            -x $(find . -type f -name "*.sh" -not -path "./templates/*")

      - name: Run shfmt
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            mvdan/shfmt@sha256:307d265ffd25ce832899ae17c93ed5062fc3375c514bba8f52cbf52792735c4d \
            -d -i 2 -ci $(find . -type f -name "*.sh" -not -path "./templates/*")

      - name: Run editorconfig-checker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            --entrypoint ec \
            mstruebing/editorconfig-checker@sha256:3fee6fe35c9ec21367b92ca50b3bea856ffc8a7a186044c329ac8bb23b33284a \
            -exclude "(\.git)"
