name: Lint

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        # Used commit SHA for actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run golangci-lint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            golangci/golangci-lint@sha256:5cceeef04e53efe1470638d4b4b4f5ceefd574955ab3941b2d9a68a8c9ad5240 \
            golangci-lint run ./...

      - name: Run yamllint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            pipelinecomponents/yamllint@sha256:3e9eb9bef568b904d9222e9174a1490f4e015aef3d61e7d3e56f60035e517b79 \
            yamllint .

      - name: Run markdownlint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            ghcr.io/igorshubovych/markdownlint-cli@sha256:c97f19b52cf7371ff767c080e3e15c15f1cbd3336fc41aeca7a93bb2cdb9843c \
            "**/*.md"

      - name: Run checkmake
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            cytopia/checkmake@sha256:23116ee551144f1021b294d3ede266ecb760272e0d6f2833f8a3d38b81beffb8 \
            Makefile

      - name: Run shellcheck
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            koalaman/shellcheck@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d \
            -x $(find . -type f -name "*.sh" -not -path "./templates/*")

      - name: Run shfmt
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            mvdan/shfmt@sha256:f22f3936140be1ba02d493b5d2b91d0e8b4af93fd903e7f46c477822bca4a3be \
            -d -i 2 -ci $(find . -type f -name "*.sh" -not -path "./templates/*")

      - name: Run editorconfig-checker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -w /workdir \
            --entrypoint ec \
            mstruebing/editorconfig-checker@sha256:af556694c3eb0a16b598efbe84c1171d40dfb779fdac6f01b89baedde065556f \
            -exclude "(\.git|\.idea|\.gitlab-ci-local|bin)"
